# Generated by Django 5.1.6 on 2025-03-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=20)),
                ('business_reg_no', models.CharField(blank=True, max_length=20)),
                ('business_address', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['profile'],
            },
        ),
    ]
