# Generated by Django 5.1.6 on 2025-03-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_merchant_acc_name_merchant_acc_no_merchant_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='business_type',
            field=models.CharField(choices=[('Select', 'Select'), ('Sales', 'Sales'), ('Services', 'Services'), ('Product_Service', 'Product_Service')], default='Select', max_length=25),
        ),
    ]
