# Generated by Django 5.1.6 on 2025-03-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('Select', 'Select'), ('Agent', 'Agent'), ('Merchant', 'Merchant'), ('Subscriber', 'Subscriber')], default='Select', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Suspended', 'Suspended')], default='Inactive', max_length=15),
        ),
    ]
