# Generated by Django 5.1.6 on 2025-03-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_role_profile_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agent_option',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='merchant_option',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscriber_option',
        ),
    ]
