# Generated by Django 5.1.6 on 2025-03-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_agent_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nin_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
