# Generated by Django 5.1.6 on 2025-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_nin_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nin',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
