# Generated by Django 5.1.6 on 2025-03-17 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('users', '0005_alter_profile_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.state'),
        ),
    ]
