# Generated by Django 5.1.6 on 2025-03-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(blank=True, max_length=20)),
                ('bank', models.CharField(blank=True, max_length=20)),
                ('acc_number', models.IntegerField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=20)),
                ('base_amount', models.IntegerField(blank=True)),
                ('charges_percentage', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
