# Generated by Django 5.1.6 on 2025-03-08 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycharges',
            name='base_amount',
            field=models.IntegerField(blank=True, help_text='Enter Base Amount'),
        ),
        migrations.AlterField(
            model_name='companycharges',
            name='charges_percentage',
            field=models.IntegerField(blank=True, default=0, help_text='Enter Percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='companycharges',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
