# Generated by Django 5.1.6 on 2025-03-06 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSetTransact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_amount', models.IntegerField(help_text='Enter Maximum Amount')),
                ('min_amount', models.IntegerField(help_text='Enter Minimum Amount')),
                ('trans_id', models.CharField(blank=True, max_length=8)),
                ('current_location', models.CharField(max_length=35)),
                ('prefered_method', models.CharField(choices=[('Card Payment', 'Card Payment'), ('Bank Transfer', 'Bank Transfer'), ('transfer_or_card', 'transfer_or_card')], default='Card Payment', max_length=50)),
                ('trans_status', models.BooleanField()),
                ('remote_option', models.BooleanField()),
                ('remark', models.TextField(max_length=35)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trans_date'],
            },
        ),
    ]
