# Generated by Django 5.1.6 on 2025-03-06 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberTransact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_amount', models.IntegerField(help_text='Enter Exam score')),
                ('current_location', models.CharField(max_length=45)),
                ('payment_method', models.CharField(choices=[('Card Payment', 'Card Payment'), ('Bank Transfer', 'Bank Transfer'), ('transfer_or_card', 'transfer_or_card')], default='Card Payment', max_length=35)),
                ('delivery_method', models.CharField(choices=[('In-Person', 'In-Person'), ('Remote Delivery', 'Remote Delivery'), ('Third Party', 'Third Party')], default='In-Person', max_length=15)),
                ('trans_status', models.BooleanField()),
                ('final_remark', models.TextField(max_length=15)),
                ('subscriber', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trans_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_ref', to='transaction.merchantsettransact')),
            ],
            options={
                'ordering': ['-trans_date'],
            },
        ),
    ]
