# Generated by Django 5.1.6 on 2025-03-06 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_subscribertransact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantsettransact',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='merchantsettransact',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subscribertransact',
            name='final_remark',
        ),
        migrations.AddField(
            model_name='merchantsettransact',
            name='trans_remark',
            field=models.TextField(default='enter a remark', max_length=35),
        ),
        migrations.AddField(
            model_name='subscribertransact',
            name='trans_remark',
            field=models.TextField(default='subscriber remark', max_length=55),
        ),
        migrations.CreateModel(
            name='TransactionComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('trans_success', models.BooleanField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trans_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='transaction.subscribertransact')),
            ],
        ),
    ]
