# Generated by Django 5.1.6 on 2025-03-12 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_companycharges_base_amount_and_more'),
        ('transaction', '0003_remove_merchantsettransact_remark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantsettransact',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchantsettransact',
            name='trans_remark',
            field=models.TextField(blank=True, default='enter a remark', max_length=35),
        ),
        migrations.AlterField(
            model_name='merchantsettransact',
            name='trans_status',
            field=models.BooleanField(blank=True),
        ),
        migrations.CreateModel(
            name='MerchantCommssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.IntegerField(help_text='Enter Maximum Amount')),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('bank_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.companybankdetail')),
                ('transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.merchantsettransact')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
