# Generated by Django 5.1.6 on 2025-03-07 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('transaction', '0003_remove_merchantsettransact_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCommssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.IntegerField(help_text='Enter Maximum Amount')),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('bank_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.companybankdetail')),
                ('transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.merchantsettransact')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
