# Generated by Django 5.1.6 on 2025-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_merchantsettransact_merchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantsettransact',
            name='trans_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
