# Generated by Django 5.1.6 on 2025-03-13 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_companycharges_base_amount_and_more'),
        ('transaction', '0007_alter_merchantsettransact_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsettransact',
            name='charges_amount_paid',
            field=models.IntegerField(blank=True, default=0, help_text='Enter Maximum Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantsettransact',
            name='charges_pay_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='merchantsettransact',
            name='comp_bank_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.companybankdetail'),
        ),
        migrations.AddField(
            model_name='merchantsettransact',
            name='payment_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
