# Generated by Django 5.1.6 on 2025-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_merchantsettransact_charges_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantsettransact',
            name='charges_amount_paid',
            field=models.IntegerField(blank=True, help_text='Enter Maximum Amount', null=True),
        ),
    ]
