# Generated by Django 5.1.6 on 2025-03-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_comment_lesson_name_order_comment_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_amount',
            field=models.IntegerField(default=0, help_text='Enter Max Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='min_amount',
            field=models.IntegerField(default=0, help_text='Enter Min Amount'),
            preserve_default=False,
        ),
    ]
